# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\"\xc5\x01\n\x0c\x45mptyExample\x12\x0e\n\x06string\x18\x01 \x01(\t\x12\r\n\x05\x61rray\x18\x02 \x03(\x05\x12\x31\n\ndictionary\x18\x03 \x03(\x0b\x32\x1d.EmptyExample.DictionaryEntry\x12\x0f\n\x07integer\x18\x04 \x01(\x04\x12\x0e\n\x06\x64ouble\x18\x05 \x01(\x01\x12\x0f\n\x07\x62oolean\x18\x06 \x01(\x08\x1a\x31\n\x0f\x44ictionaryEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xe2\x01\n\x07\x45xample\x12\x0e\n\x06string\x18\x01 \x01(\t\x12\r\n\x05\x61rray\x18\x02 \x03(\x05\x12,\n\ndictionary\x18\x03 \x03(\x0b\x32\x18.Example.DictionaryEntry\x12\x0f\n\x07integer\x18\x04 \x01(\x04\x12\x0e\n\x06\x64ouble\x18\x05 \x01(\x01\x12\x0f\n\x07\x62oolean\x18\x06 \x01(\x08\x12%\n\x0e\x65mpty_subclass\x18\x07 \x01(\x0b\x32\r.EmptyExample\x1a\x31\n\x0f\x44ictionaryEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTYEXAMPLE_DICTIONARYENTRY._options = None
  _EMPTYEXAMPLE_DICTIONARYENTRY._serialized_options = b'8\001'
  _EXAMPLE_DICTIONARYENTRY._options = None
  _EXAMPLE_DICTIONARYENTRY._serialized_options = b'8\001'
  _EMPTYEXAMPLE._serialized_start=18
  _EMPTYEXAMPLE._serialized_end=215
  _EMPTYEXAMPLE_DICTIONARYENTRY._serialized_start=166
  _EMPTYEXAMPLE_DICTIONARYENTRY._serialized_end=215
  _EXAMPLE._serialized_start=218
  _EXAMPLE._serialized_end=444
  _EXAMPLE_DICTIONARYENTRY._serialized_start=166
  _EXAMPLE_DICTIONARYENTRY._serialized_end=215
# @@protoc_insertion_point(module_scope)
